#!/usr/bin/env bash
set -aeuo pipefail

source .env

# set COMPOSE_PROJECT_NAME environment variable that will be used by the networks
COMPOSE_PROJECT_NAME="${PROJECT}_${ENVIRONMENT}"
VERSION=$(cat VERSION)

echo "stop modules"
docker-compose down
