# networks:
#   default:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: ${DOCKER_NETWORK_IPAM_SUBNET}
#           gateway: ${DOCKER_NETWORK_IPAM_GATEWAY}

services:
  wordpress_frankenphp:
    image: yao3060/wordpress-frankenphp:php8.3
    restart: always
    env_file: .env
    environment:
      SERVER_NAME: ${SERVER_NAME:-:8000}
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-domain}
      WP_REDIS_HOST: wordpress_cache
    ports:
      - "${WORDPRESS_HTTP_PORT:-8000}:8000"
    volumes:
      - wordpress-uploads:/var/www/html/wp-content/uploads
      - caddy-data:/data
      - caddy-config:/config

  wordpress_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-domain}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
    volumes:
      - wordpress-db:/var/lib/mysql

  wordpress_cache:
    image: redis:alpine
    restart: always
    volumes:
      - wordpress-cache:/data


volumes:
  wordpress-uploads:
  wordpress-db:
  wordpress-cache:
  # Caddy 证书和配置所需的挂载目录
  caddy-data:
  caddy-config:

