#!/bin/bash

########################
# PREPARE INSTALLATION #
########################

# Install needed plugins
wp plugin install acf-to-rest-api --activate
wp plugin install advanced-custom-fields --activate
wp plugin install breadcrumb-trail --activate
wp plugin install wp-rest-api-cache --activate
wp plugin install wp-rest-api-frontpage --activate
wp plugin install wp-api-menus --activate
wp plugin install wp-rest-api-sidebars --activate

# install private plugins
git clone ssh://git@git.it-consultis.net:22080/wordpress/itc-rest-api-ext.git wp-content/plugins/itc-rest-api-ext
rm -rf wp-content/plugins/itc-rest-api-ext/.git
wp plugin activate itc-rest-api-ext 

# Create empty theme
mkdir -p wp-content/themes/rest/

echo "/*					                   "  > wp-content/themes/rest/style.css
echo "	Theme Name: Rest			                   " >> wp-content/themes/rest/style.css
echo "	Theme URI: https://it-consultis.com	                   " >> wp-content/themes/rest/style.css
echo "	Description: Rest API start theme	                   " >> wp-content/themes/rest/style.css
echo "	Version: 1.0.0				                   " >> wp-content/themes/rest/style.css
echo "	Author: IT Consultis			                   " >> wp-content/themes/rest/style.css
echo "	Author URI: https://it-consultis.com	                   " >> wp-content/themes/rest/style.css
echo "	Tags: Blank, Rest API			                   " >> wp-content/themes/rest/style.css
echo "						                   " >> wp-content/themes/rest/style.css
echo "	License: MIT						   " >> wp-content/themes/rest/style.css
echo "	License URI: http://opensource.org/licenses/mit-license.php" >> wp-content/themes/rest/style.css
echo "*/							   " >> wp-content/themes/rest/style.css

echo "<?php" > wp-content/themes/rest/index.php
echo "<?php" > wp-content/themes/rest/functions.php
echo "<?php" > wp-content/themes/rest/comments.php

wp theme activate rest

wp rewrite structure '/%postname%/' --hard

###########
# CLEANUP #
###########

# Remove useless plugins
wp plugin delete hello
wp plugin delete akismet

# Remove old themes
wp theme delete twentyfifteen
wp theme delete twentysixteen
wp theme delete twentyseventeen 

# Remove default data
wp site empty --yes
