version: '2.3'

services:
  wordpress_apache:
    build:
      context: .
      dockerfile: ./src-wordpress/.docker/apache/Dockerfile
      args:
        WORDPRESS_VERSION: ${WORDPRESS_VERSION}
        CACHE_DATE: "${CACHE_DATE}"
        DOCKER_HOST_UID: ${DOCKER_HOST_UID}
        XDEBUG: ${WORDPRESS_XDEBUG}
        INSTALL_SENDMAIL: 0
    environment:
      XDEBUG_CONFIG: remote_host=$XDEBUG_IP_ADDRESS remote_port=$XDEBUG_REMOTE_PORT
      DEV_ENV: 1
    env_file:
      - .env
    volumes:
      - wordpress_source:/var/www/html
      - ./src-wordpress/src/wp-content:/var/www/html/wp-content
      - ./src-wordpress/src/wp-config-sample.php:/usr/src/wordpress/wp-config-sample.php
      - ./src-wordpress/src/index.php:/usr/src/wordpress/index.php
      - ./src-wordpress/src/.htaccess:/usr/src/wordpress/.htaccess
      - ./.env:/usr/src/wordpress/.env

  wordpress_db:
    ports:
      - 3306
    volumes:
      - ./src-wordpress/transfer:/docker-entrypoint-initdb.d

  wordpress_cli:
    image: wordpress:cli
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress_cli
    volumes:
      - wordpress_source:/var/www/html
      - ./src-wordpress/src/wp-content:/var/www/html/wp-content
      - ./src-wordpress/src/wp-config-sample.php:/usr/src/wordpress/wp-config-sample.php
      - ./src-wordpress/src/index.php:/usr/src/wordpress/index.php
      - ./src-wordpress/src/.htaccess:/usr/src/wordpress/.htaccess
      - ./.env:/usr/src/wordpress/.env
    command: ["tail", "-f", "/dev/null"]

volumes:
  wordpress_source:
